### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by ozkanAdar** [Nolkeg/PlacenoteAR#1]
Hello. I have checked your updated edition. What do I need to do in order to make it work. Do I need to replace your files with Mathew's originals?

**Comment by Nolkeg** [comment]
Hi, just open the test scene in test folder. 
It’s all in one scene. You can try to play in editor before build. 
When you want to build, just add your api key to camera. And did the basic setting like matthew did. 
Let me know if there are any problems. and it would be really great if you can give me some suggestion on where to improve

**Comment by Nolkeg** [comment]
In the latest commit, I'd saved the setting to master already. It should have the correct setting ready for build now. You only need to change the api key and bundle identifier to yours.

**Comment by ozkanAdar** [comment]
Wow! I just checked the test scene without building but I can say you had many improvements already!
I will check on phone to see. After I will edit here my opinions!

**Comment by Nolkeg** [comment]
You can add me on facebook 
@Jiraphat Orachaipunlap
As for your question, I believe It is possible. You could try searching for how to create mini map in Unity in youtube. I'm working on improving UI, add more content to destination(description of each destination) which will show up after tapping the shape and spatially linked map.

**Comment by SantoshD07** [comment]
@Nolkeg What are the unity and the IOS version that you were working with?
